name: Firebase Deploy Workflow

on:
  push:
    branches:
      - master  # Auto-deploys to DEV_ENV on merge
  workflow_dispatch:  # Allows manual trigger for PROD_ENV

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Angular App (DEV_ENV)
        run: npm run build -- --configuration=development

      - name: Authenticate Firebase
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV

      - name: Deploy to Firebase DEV_ENV
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:expense-tracker-1ff01-dev
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

  deploy-prod:
    runs-on: ubuntu-latest
    environment: PROD
    needs: deploy-dev
    if: github.event_name == 'workflow_dispatch'  # Only runs when triggered manually
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Angular App (PROD_ENV)
        run: npm run build -- --configuration=production

      - name: Authenticate Firebase
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV

      - name: Deploy to Firebase PROD_ENV
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:expense-tracker-1ff01
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
