name: Firebase Deploy Workflow

on:
  push:
    branches:
      - master  # Auto-deploys to DEV
  workflow_dispatch:  # Allows manual trigger for PROD

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Angular App (DEV_ENV)
        run: npm run build -- --configuration=development

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Decode Firebase Service Account
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" | base64 --decode > $HOME/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV

      - name: Authenticate Firebase
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV
          chmod 600 $HOME/firebase-key.json  

      - name: Deploy to Firebase
        run: firebase deploy --only hosting:expense-tracker-1ff01-dev
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json

  deploy-prod:
    runs-on: ubuntu-latest
    environment: PROD
    needs: deploy-dev
    if: github.event_name == 'workflow_dispatch'  # Only runs when triggered manually
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Angular App (PROD_ENV)
        run: npm run build -- --configuration=production

      - name: Authenticate Firebase
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV
          cat $HOME/firebase-key.json  # Debugging line to verify JSON content

      - name: Deploy to Firebase PROD_ENV
        run: |
          firebase deploy --only hosting:expense-tracker-1ff01 --token "$(cat $HOME/firebase-key.json)"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json
