name: Firebase Deploy Workflow

on:
  push:
    branches:
      - master  # Auto-deploys to DEV on merge
  workflow_dispatch:  # Allows manual trigger for PROD

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: echo "✅ Checked out repository"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: echo "✅ Node.js setup complete"

      - name: Install dependencies
        run: npm ci
      - run: echo "✅ Dependencies installed"

      - name: Build Angular App (DEV)
        run: npm run build -- --configuration=development
      - run: echo "✅ Angular build completed for DEV"

      - name: Write Firebase Credentials to JSON
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $GITHUB_WORKSPACE/firebase.json
      - run: echo "✅ Firebase credentials JSON created"

      - name: Setup Firebase CLI
        run: npm install -g firebase-tools
      - run: echo "✅ Firebase CLI installed"

      - name: Deploy to Firebase DEV
        run: firebase deploy --only hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $GITHUB_WORKSPACE/firebase.json
      - run: echo "✅ Deployment to Firebase DEV completed"

  deploy-prod:
    runs-on: ubuntu-latest
    environment: PROD
    if: github.event_name == 'workflow_dispatch'  # Only runs when triggered manually
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: echo "✅ Checked out repository"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: echo "✅ Node.js setup complete"

      - name: Install dependencies
        run: npm ci
      - run: echo "✅ Dependencies installed"

      - name: Build Angular App (PROD)
        run: npm run build -- --configuration=production
      - run: echo "✅ Angular build completed for PROD"

      - name: Write Firebase Credentials to JSON
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $GITHUB_WORKSPACE/firebase.json
      - run: echo "✅ Firebase credentials JSON created"

      - name: Setup Firebase CLI
        run: npm install -g firebase-tools
      - run: echo "✅ Firebase CLI installed"

      - name: Deploy to Firebase PROD
        run: firebase deploy --only hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $GITHUB_WORKSPACE/firebase.json
      - run: echo "✅ Deployment to Firebase PROD completed"
