name: Firebase Deploy Workflow

on:
  push:
    branches:
      - master  # Auto-deploys to DEV
  workflow_dispatch:  # Allows manual trigger for PROD

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Angular App (DEV_ENV)
        run: npm run build -- --configuration=development

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting (DEV)
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json
          firebase deploy --only hosting:expense-tracker-1ff01-dev --non-interactive
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json

  deploy-prod:
    runs-on: ubuntu-latest
    environment: PROD
    needs: deploy-dev
    if: github.event_name == 'workflow_dispatch'  # Only runs when triggered manually
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Angular App (PROD_ENV)
        run: npm run build -- --configuration=production

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting (PROD)
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json
          firebase deploy --only hosting:expense-tracker-1ff01 --non-interactive
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json